### ISSUE TITLE
Installer on Windows: exceeded the timeout of 60 seconds, and failed renaming application

### ISSUE THREAD

**Issue by emmajiugo** [laravel-zero/laravel-zero#184]
```
What is your application name?:
 >

  Aborted


Script @php application app:rename handling the post-create-project-cmd event returned with error code 1
```

I keep getting the above error anytime I tried installing Laravel-Zero using `composer create-project --prefer-dist laravel-zero/laravel-zero movie-cli`

**Comment by emmajiugo** [comment]
Also using the `laravel-zero` installer, I keep getting this below error:

```
In Process.php line 1160:
                                                                               
  The process "composer create-project laravel-zero/laravel-zero rave --prefer-dist" exceeded the timeout of 60 secon
  ds.                                                                          
```

**Comment by nunomaduro** [comment]
@emmajiugo Try to use directly this `composer create-project laravel-zero/laravel-zero rave --prefer-dist`. And tell me the results.

**Comment by emmajiugo** [comment]
> @emmajiugo Try to use directly this `composer create-project laravel-zero/laravel-zero rave --prefer-dist`. And tell me the results.

It aborted, same as when using `Via Composer Create-Project`. Gave the below error after trying to rename the application:

```
Generating optimized autoload files
> @php application app:rename
Renaming the application...

 What is your application name?:
 >

  Aborted


Script @php application app:rename handling the post-create-project-cmd event returned with error code 1

```

**Comment by emmajiugo** [comment]
@nunomaduro I still need a fix on the above issue.

But a temporary fix I did was; I discovered that the default name given is `application`. So I ran the command ` php application app:rename <your-app-name>`

This was home I gave my app a unique name.

**Comment by nunomaduro** [comment]
Installer project: https://github.com/laravel-zero/installer.

Code related to the rename: https://github.com/laravel-zero/laravel-zero/blob/4b04bdcb69dc6e92983c45865a0637f5cce84402/composer.json#L46

**Comment by tvbeek** [comment]
For issue 2 it is possible for testing and debugging to rename / copy the post-create-project-cmd to a script with another name and call that script with composer scriptname. That result in the same error as during the create-project command.

I tracked it to the QuestionHelper where it didn't have autocomplete and Stty: https://github.com/symfony/console/blob/master/Helper/QuestionHelper.php#L114

**Comment by nunomaduro** [comment]
Related issue: https://github.com/laravel-zero/laravel-zero/issues/175

**Comment by shadoWalker89** [comment]
Problem solved by increasing the php.ini config value `default_socket_timeout` to bigger value

**Comment by KhanMaytok** [comment]
> Issue 1: Using the Laravel Zero installer - https://github.com/laravel-zero/installer - the following error keeps happening while using windows:
> 
> ```
>                                                                                
>   The process "composer create-project laravel-zero/laravel-zero rave --prefer-dist" exceeded the timeout of 60 seconds.
> ```
> **Solution**: Set timeout to `0` on the symfony process created to install Laravel Zero.
> 

How can I set the timeout to 0?

**Comment by paKanhu** [comment]
@nunomaduro This issue is related to [https://github.com/laravel/framework/issues/28344](https://github.com/laravel/framework/issues/28344). I tried by following below process and it worked.

1. `composer create-project --prefer-dist --no-scripts laravel-zero/laravel-zero movie-cli`
2. `cd movie-cli`
3. `composer config repositories.illuminate/config '{"type": "git", "url": "https://github.com/illuminate/config"}'`
4. `composer require illuminate/config:5.8.9`
5. `php application app:rename`

**Comment by isaackearl** [comment]
> > Issue 1: Using the Laravel Zero installer - https://github.com/laravel-zero/installer - the following error keeps happening while using windows:
> > ```
> >                                                                                
> >   The process "composer create-project laravel-zero/laravel-zero rave --prefer-dist" exceeded the timeout of 60 seconds.
> > ```
> > 
> > 
> > **Solution**: Set timeout to `0` on the symfony process created to install Laravel Zero.
> 
> How can I set the timeout to 0?

I also cannot figure this out.  Any help would be appreciated.

**Comment by owenvoke** [comment]
It looks like the rename issue should be resolved in Composer v2 (https://github.com/composer/composer/commit/f5726366286b9e2765dfe4947fa825701f306737), however this still may not work on Windows. 😕

**Comment by dimasahmad** [comment]
It's still not working on windows, the timeout and rename problem still exist

**Comment by owenvoke** [comment]
The rename script has been removed from Composer, and is now a manual process after installation (unless using the [Laravel Zero Installer](https://laravel-zero.com/docs/installation#via-the-laravel-zero-installer) at v2.5 or later).

I'm going to close this as I don't think it's relevant anymore. 👍🏻 Any further problems, feel free to open a new issue.
