### ISSUE TITLE
Issue when installing for first time, Process.php line 1236 times out and throws an error

### ISSUE THREAD

**Issue by nikocraft** [laravel-zero/laravel-zero#213]
It not possible for me to install it without this process throwing a message.

Here are some logs:
```
λ laravel-zero new laratheme
Crafting application..

Installing laravel-zero/laravel-zero (v5.8.5)
  - Installing laravel-zero/laravel-zero (v5.8.5): Downloading (100%)
Created project in laratheme
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 66 installs, 0 updates, 0 removals
  - Installing symfony/polyfill-php72 (v1.11.0): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.11.0): Loading from cache
  - Installing symfony/var-dumper (v4.2.8): Downloading (100%)
  - Installing symfony/process (v4.2.8): Loading from cache
  - Installing psr/log (1.1.0): Loading from cache
  - Installing symfony/debug (v4.2.8): Loading from cache
  - Installing symfony/contracts (v1.1.0): Downloading (100%)
  - Installing symfony/console (v4.2.8): Loading from cache
  - Installing jolicode/jolinotif (v2.0.2): Downloading (100%)
  - Installing symfony/translation (v4.2.8): Downloading (100%)
  - Installing nesbot/carbon (2.17.1): Downloading (100%)

In Process.php line 1236:

  The process "composer create-project laravel-zero/laravel-zero laratheme --prefer-dist" exceeded the timeout of 60 seconds.
```

After trying again, I come longer
```
λ laravel-zero new laratheme
Crafting application..

Installing laravel-zero/laravel-zero (v5.8.5)
  - Installing laravel-zero/laravel-zero (v5.8.5): Loading from cache
Created project in laratheme
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 66 installs, 0 updates, 0 removals
  - Installing symfony/polyfill-php72 (v1.11.0): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.11.0): Loading from cache
  - Installing symfony/var-dumper (v4.2.8): Loading from cache
  - Installing symfony/process (v4.2.8): Loading from cache
  - Installing psr/log (1.1.0): Loading from cache
  - Installing symfony/debug (v4.2.8): Loading from cache
  - Installing symfony/contracts (v1.1.0): Loading from cache
  - Installing symfony/console (v4.2.8): Loading from cache
  - Installing jolicode/jolinotif (v2.0.2): Loading from cache
  - Installing symfony/translation (v4.2.8): Loading from cache
  - Installing nesbot/carbon (2.17.1): Loading from cache
  - Installing psr/simple-cache (1.0.1): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing illuminate/contracts (v5.8.15): Downloading (100%)
  - Installing doctrine/inflector (v1.3.0): Loading from cache
  - Installing illuminate/support (v5.8.15): Downloading (100%)
  - Installing illuminate/console (v5.8.15): Downloading (100%)
  - Installing nunomaduro/laravel-desktop-notifier (v2.1.0): Downloading (100%)
  - Installing nunomaduro/laravel-console-task (v1.2.0): Downloading (100%)
  - Installing nunomaduro/laravel-console-summary (v1.1.0): Downloading (100%)
  - Installing jakub-onderka/php-console-color (v0.2): Downloading (100%)
  - Installing jakub-onderka/php-console-highlighter (v0.4): Loading from cache
  - Installing filp/whoops (2.3.1): Downloading (100%)
  - Installing nunomaduro/collision (v3.0.1): Downloading (100%)
  - Installing league/flysystem (1.0.51): Loading from cache
  - Installing laravel-zero/foundation (v5.8.8): Downloading (100%)
  - Installing symfony/finder (v4.2.8): Loading from cache
  - Installing illuminate/filesystem (v5.8.15): Downloading (100%)
  - Installing symfony/polyfill-ctype (v1.11.0): Loading from cache
  - Installing phpoption/phpoption (1.5.0): Downloading (100%)
  - Installing vlucas/phpdotenv (v3.3.3): Downloading (100%)
  - Installing illuminate/container (v5.8.15): Downloading (100%)
  - Installing illuminate/events (v5.8.15): Downloading (100%)
  - Installing illuminate/config (v5.8.15): Downloading (100%)
  - Installing illuminate/cache (v5.8.15): Downloading (100%)
  - Installing dragonmantank/cron-expression (v2.3.0): Loading from cache
  - Installing laravel-zero/framework (v5.8.5): Downloading (connecting...)
In Process.php line 1236:

  The process "composer create-project laravel-zero/laravel-zero laratheme --prefer-dist" exceeded the timeout of 60 seconds.
```

Each time I would get further but process.php would throw error. At the end I think I installed everything but upon "Generating optimized autoload files" same error was thrown. Here is 
the last log, where everything is installed, but error is thrown.

```
λ laravel-zero new laratheme
Crafting application..

Installing laravel-zero/laravel-zero (v5.8.5)
  - Installing laravel-zero/laravel-zero (v5.8.5): Loading from cache
Created project in laratheme
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 66 installs, 0 updates, 0 removals
  - Installing symfony/polyfill-php72 (v1.11.0): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.11.0): Loading from cache
  - Installing symfony/var-dumper (v4.2.8): Loading from cache
  - Installing symfony/process (v4.2.8): Loading from cache
  - Installing psr/log (1.1.0): Loading from cache
  - Installing symfony/debug (v4.2.8): Loading from cache
  - Installing symfony/contracts (v1.1.0): Loading from cache
  - Installing symfony/console (v4.2.8): Loading from cache
  - Installing jolicode/jolinotif (v2.0.2): Loading from cache
  - Installing symfony/translation (v4.2.8): Loading from cache
  - Installing nesbot/carbon (2.17.1): Loading from cache
  - Installing psr/simple-cache (1.0.1): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing illuminate/contracts (v5.8.15): Loading from cache
  - Installing doctrine/inflector (v1.3.0): Loading from cache
  - Installing illuminate/support (v5.8.15): Loading from cache
  - Installing illuminate/console (v5.8.15): Loading from cache
  - Installing nunomaduro/laravel-desktop-notifier (v2.1.0): Loading from cache
  - Installing nunomaduro/laravel-console-task (v1.2.0): Loading from cache
  - Installing nunomaduro/laravel-console-summary (v1.1.0): Loading from cache
  - Installing jakub-onderka/php-console-color (v0.2): Loading from cache
  - Installing jakub-onderka/php-console-highlighter (v0.4): Loading from cache
  - Installing filp/whoops (2.3.1): Loading from cache
  - Installing nunomaduro/collision (v3.0.1): Loading from cache
  - Installing league/flysystem (1.0.51): Loading from cache
  - Installing laravel-zero/foundation (v5.8.8): Loading from cache
  - Installing symfony/finder (v4.2.8): Loading from cache
  - Installing illuminate/filesystem (v5.8.15): Loading from cache
  - Installing symfony/polyfill-ctype (v1.11.0): Loading from cache
  - Installing phpoption/phpoption (1.5.0): Loading from cache
  - Installing vlucas/phpdotenv (v3.3.3): Loading from cache
  - Installing illuminate/container (v5.8.15): Loading from cache
  - Installing illuminate/events (v5.8.15): Loading from cache
  - Installing illuminate/config (v5.8.15): Loading from cache
  - Installing illuminate/cache (v5.8.15): Loading from cache
  - Installing dragonmantank/cron-expression (v2.3.0): Loading from cache
  - Installing laravel-zero/framework (v5.8.5): Loading from cache
  - Installing hamcrest/hamcrest-php (v2.0.0): Loading from cache
  - Installing mockery/mockery (1.2.2): Loading from cache
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/resource-operations (2.0.1): Loading from cache
  - Installing sebastian/object-reflector (1.1.1): Loading from cache
  - Installing sebastian/recursion-context (3.0.0): Loading from cache
  - Installing sebastian/object-enumerator (3.0.3): Loading from cache
  - Installing sebastian/global-state (2.0.0): Loading from cache
  - Installing sebastian/exporter (3.1.0): Loading from cache
  - Installing sebastian/environment (4.2.2): Loading from cache
  - Installing sebastian/diff (3.0.2): Loading from cache
  - Installing sebastian/comparator (3.0.2): Loading from cache
  - Installing phpunit/php-timer (2.1.1): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/php-file-iterator (2.0.2): Loading from cache
  - Installing theseer/tokenizer (1.1.2): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
  - Installing phpunit/php-token-stream (3.0.1): Loading from cache
  - Installing phpunit/php-code-coverage (6.1.4): Downloading (100%)
  - Installing doctrine/instantiator (1.2.0): Loading from cache
  - Installing webmozart/assert (1.4.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (4.3.1): Downloading (100%)
  - Installing phpspec/prophecy (1.8.0): Loading from cache
  - Installing phar-io/version (2.0.1): Downloading (100%)
  - Installing phar-io/manifest (1.0.3): Downloading (100%)
  - Installing myclabs/deep-copy (1.9.1): Loading from cache
  - Installing phpunit/phpunit (7.5.10): Downloading (100%)
symfony/contracts suggests installing psr/cache (When using the Cache contracts)
symfony/contracts suggests installing symfony/cache-contracts-implementation ()
symfony/contracts suggests installing symfony/event-dispatcher-implementation ()
symfony/contracts suggests installing symfony/http-client-contracts-implementation ()
symfony/contracts suggests installing symfony/service-contracts-implementation ()
symfony/console suggests installing symfony/event-dispatcher ()
symfony/console suggests installing symfony/lock ()
symfony/translation suggests installing symfony/config ()
symfony/translation suggests installing symfony/yaml ()
illuminate/support suggests installing moontoast/math (Required to use ordered UUIDs (^1.1).)
illuminate/support suggests installing ramsey/uuid (Required to use Str::uuid() (^3.7).)
illuminate/console suggests installing guzzlehttp/guzzle (Required to use the ping methods on schedules (^6.0).)
filp/whoops suggests installing whoops/soap (Formats errors as SOAP responses)
league/flysystem suggests installing league/flysystem-eventable-filesystem (Allows you to use EventableFilesystem)
league/flysystem suggests installing league/flysystem-rackspace (Allows you to use Rackspace Cloud Files)
league/flysystem suggests installing league/flysystem-azure (Allows you to use Windows Azure Blob storage)
league/flysystem suggests installing league/flysystem-webdav (Allows you to use WebDAV storage)
league/flysystem suggests installing league/flysystem-aws-s3-v2 (Allows you to use S3 storage with AWS SDK v2)
league/flysystem suggests installing league/flysystem-aws-s3-v3 (Allows you to use S3 storage with AWS SDK v3)
league/flysystem suggests installing spatie/flysystem-dropbox (Allows you to use Dropbox storage)
league/flysystem suggests installing srmklive/flysystem-dropbox-v2 (Allows you to use Dropbox storage for PHP 5 applications)
league/flysystem suggests installing league/flysystem-cached-adapter (Flysystem adapter decorator for metadata caching)
league/flysystem suggests installing league/flysystem-sftp (Allows you to use SFTP server storage via phpseclib)
league/flysystem suggests installing league/flysystem-ziparchive (Allows you to use ZipArchive adapter)
illuminate/filesystem suggests installing league/flysystem-aws-s3-v3 (Required to use the Flysystem S3 driver (^1.0).)
illuminate/filesystem suggests installing league/flysystem-cached-adapter (Required to use the Flysystem cache (^1.0).)
illuminate/filesystem suggests installing league/flysystem-rackspace (Required to use the Flysystem Rackspace driver (^1.0).)
illuminate/filesystem suggests installing league/flysystem-sftp (Required to use the Flysystem SFTP driver (^1.0).)
illuminate/cache suggests installing illuminate/database (Required to use the database cache driver (5.8.*).)
illuminate/cache suggests installing illuminate/redis (Required to use the redis cache driver (5.8.*).)
sebastian/global-state suggests installing ext-uopz (*)
sebastian/environment suggests installing ext-posix (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.6.0)
phpunit/phpunit suggests installing phpunit/php-invoker (^2.0)
phpunit/phpunit suggests installing ext-xdebug (*)
Writing lock file
Generating optimized autoload files

In Process.php line 1236:

  The process "composer create-project laravel-zero/laravel-zero laratheme --prefer-dist" exceeded the timeout of 60 seconds.
```

What can be done about the error, can I use the application now even though it ended with the error above?

**Comment by juniorb2ss** [comment]
Take a look on this: https://github.com/laravel-zero/laravel-zero/issues/184

**Comment by nunomaduro** [comment]
This issue has been fixed long time ago, please perform `composer global update laravel-zero/installer` and try again?

**Comment by nikocraft** [comment]
I just installed laravel-zero today, so I must have the latest version. Obviously, something is still wrong? :)

**Comment by abdulrahman19** [comment]
I have the same issue, I've just installed the Laravel zero, I have the latest version, but still gives me the same error in WIN 10.

Any help :/

**Comment by owenvoke** [comment]
Is anyone still experiencing this issue now? 🤔 I've been unable to replicate it in later versions.

**Comment by nunomaduro** [comment]
This issue seems old.
