### ISSUE TITLE
Cannot build any package

### ISSUE THREAD

**Issue by Tjoosten** [laravel-zero/laravel-zero#230]
If i run php application app:build application
 

I get the follwing in return:

 Build version? [unreleased]:
 >

   1. Moving application to production mode: ✔
   2. Compile into a single file: ✔

   ErrorException  : rename(C:\Users\Gebruiker\Documents\warror\application.phar,C:\Users\Gebruiker\Documents\warror\builds\application): Het systeem kan het opgegeven bestand niet vinden. (code: 2)

  at C:\Users\Gebruiker\Documents\warror\vendor\illuminate\filesystem\Filesystem.php:227
    223|      * @return bool
    224|      */
    225|     public function move($path, $target)
    226|     {
  > 227|         return rename($path, $target);
    228|     }
    229| 
    230|     /**
    231|      * Copy a file to a new location.

  Exception trace:

  1   rename("C:\Users\Gebruiker\Documents\warror\application.phar", "C:\Users\Gebruiker\Documents\warror\builds\application")
      C:\Users\Gebruiker\Documents\warror\vendor\illuminate\filesystem\Filesystem.php:227

  2   Illuminate\Filesystem\Filesystem::move("C:\Users\Gebruiker\Documents\warror\application.phar", "C:\Users\Gebruiker\Documents\warror\builds\application")
      C:\Users\Gebruiker\Documents\warror\vendor\illuminate\support\Facades\Facade.php:237

  Please use the argument -v to see more details.

**Comment by eppak** [comment]
Hello,
same here, i fixed changing permission to box script, trt this (from you project root):

`#chmod 755 vendor/laravel-zero/framework/bin/box`

Hope this help.

**Comment by thomasbuckle-uk** [comment]
I'm also getting this error, running Windows 10 & Git Bash. Tried all the fixes I can find.

**Comment by nunomaduro** [comment]
@thomasbuckle-uk Can you make a pull request against the `6.0`?

**Comment by pxgamer** [comment]
This seems to be fixed with the latest Box binary. I'll make a PR shortly with the new PHAR. :+1:

**Comment by nunomaduro** [comment]
Process is download the https://github.com/humbug/box/releases the phar. Add it to the bin folder. Don't forget to set permissions to 755 and of course test it a little bit with our components.

**Comment by arnoldkunihira** [comment]
> Process is download the https://github.com/humbug/box/releases the phar. Add it to the bin folder. Don't forget to set permissions to 755 and of course test it a little bit with our components.

I am using windows and did exactly what you have recommended, however I downloaded the box.phar file and pasted it in vendor\laravel-zero\framework\bin then set the permissions as you suggested but the app:build still throws the ErrorException.

Any solutions please.

**Comment by pxgamer** [comment]
@arnoldkunihira, I think Nuno was meaning that's the process for us updating the Box binary (I've opened laravel-zero/framework#371).

See laravel-zero/framework#348 which I'm looking into at the moment which should fix the issue (although I feel that not requiring a global install, as mentioned in my comment, would be a better implementation).

**Comment by arnoldkunihira** [comment]
@pxgamer, I am still getting the same error when I run app:build on windows, however, once you get the solution, could you at least provide a step by step solution for us windows users (been on this error for 4 days). 
I will be glad if It is solved once and for all.

**Comment by sarthaksavvy** [comment]
Is there any fixed solution, having exactly the same issue

**Comment by pxgamer** [comment]
Hi @sarthaksavvy, sorry for the delayed reply. I'm hoping to have laravel-zero/framework#348 merged soon, however haven't received a reply. I'll ask if it's ok to apply some changes to the PR and then we should be good to go. 👍

**Comment by FujiMakoto** [comment]
Experiencing the same issue myself again after updating to Laravel Zero 6.0
![image](https://user-images.githubusercontent.com/7929996/74098156-af293880-4ae2-11ea-984b-d981e2d33792.png)
Doesn't work on Windows or when running the command via bash. Fails every time with the following error,

```
In Box.php line 74:

  chdir(): No such file or directory (errno 2)


compile [-c|--config CONFIG] [--debug] [--no-parallel] [--no-restart] [--dev] [--no-config] [--with-docker] [-d|--working-dir WORKING-DIR]

   2. Compile into a single file: ✔


   ErrorException  : rename(/mnt/c/Users/makoto/Code/invision-dev-helper/invision dev helper.phar,/mnt/c/Users/makoto/Code/invision-dev-helper/builds/invision dev helper): No such file or directory

  at /mnt/c/Users/makoto/Code/invision-dev-helper/vendor/illuminate/filesystem/Filesystem.php:238
    234|      * @return bool
    235|      */
    236|     public function move($path, $target)
    237|     {
  > 238|         return rename($path, $target);
    239|     }
    240| 
    241|     /**
    242|      * Copy a file to a new location.

```

Fails when Github tries to build it using Github Actions too.
https://github.com/FujiMakoto/ips-dev-helper/runs/434262097?check_suite_focus=true

**Comment by FujiMakoto** [comment]
Alright, so it looks like this may just be a weird permissions issue with the Linux Subsystem on Windows.

Running the build as root fixes it.

The build on Github is failing because it seems laravel-zero is not yet compatible with php7.4,

`PHP Parse error:  syntax error, unexpected 'fn' (T_FN), expecting identifier (T_STRING)`

**Comment by owenvoke** [comment]
Box was updated to support PHP 7.4 in v6.1.0 of Laravel Zero framework. From the `composer.lock`, it looks like v6.0.0 is being used.

Could you try updating using `composer update laravel-zero/framework` and see if the problem persists?

**Comment by mrzainulabideen** [comment]
I had the same issue with laravel-zero/framework 7.0.
For me the issue was with the path of box file
The command php %~dp0/box %* does not get names with spaces in them so i used this php "%~dp0box" %*
I would suggest that this would be incorporated in the code or should i do the PR?

**Comment by abkrim** [comment]
Same.

On linux box, when use command

```
php cpanel-api app:build --build-version=1.0

 Building process                
                                                

   1. Moving application to production mode: ✔
   2. Compile into a single file: ✔

[2020-05-20 14:56:22] development.ERROR: rename(/root/cpanel-api/cpanel-api.phar,/root/cpanel-api/builds/cpanel-api): No such file or directory {"exception":"[object] (ErrorException(code: 0): rename(/root/cpanel-api/cpanel-api.phar,/root/cpanel-api/builds/cpanel-api): No such file or directory at /root/cpanel-api/vendor/illuminate/filesystem/Filesystem.php:238)
[stacktrace]
....

 rename(/root/cpanel-api/cpanel-api.phar,/root/cpanel-api/builds/cpanel-api): No such file or directory

  at vendor/illuminate/filesystem/Filesystem.php:238
    234|      * @return bool
    235|      */
    236|     public function move($path, $target)
    237|     {
  > 238|         return rename($path, $target);
    239|     }
    240|
    241|     /**
    242|  
```

**Comment by tomasnorre** [comment]
I had the some issue today, the problem for me was a missing php dependency, the `php-intl` 
The command from @rdelafuente helped my figuring that out. 

```shell
./vendor/laravel-zero/framework/bin/box compile --working-dir=/path/to/your/project --config=/path/to/your/project/box.json --debug
``` 

The `-v` on the build command would also have done the trick, but Roberto pointed me into the right direction. 
Thanks.

**Comment by abnerisrael** [comment]
Yes @tomasnorre  and @rdelafuente this worked for me too! thanks.

**Comment by owenvoke** [comment]
@Broutard, I've just released v8.9.0 which should resolve the Box issue (updated to v3.13.0 of Box). 👍🏻

**Comment by Shelob9** [comment]
I ran into this issue with laravel-zero/framework, version "v8.9.1", PHP 8.0 in Debian (running in Windows 10.)

I ran the command again with ---vvv, which showed a permissions issue. I ran `chmod 755 vendor/laravel-zero/framework/bin/box`  as @eppak suggested here: https://github.com/laravel-zero/laravel-zero/issues/230#issuecomment-502701572 

After doing that, I was able to make a build.
