### ISSUE TITLE
Exiting the "app:build" command removes/clears the "box.json" file

### ISSUE THREAD

**Issue by nunomaduro** [laravel-zero/laravel-zero#338]
Just noticed that if we leave the command "app:build" with a control + C, that actually clears the "box.json" file.

```
➜ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
➜ php laracon-schedule app:build


                Building process


 Build version? [v1.3.0]:
 > ^C^C
➜ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   box.json
```

**Comment by owenvoke** [comment]
I thought this was solved by [this code](https://github.com/laravel-zero/framework/blob/7e92a2d11a7d4963753d806b2cef217544198b93/src/Commands/BuildCommand.php#L65) where it should catch the usage of `SIGINT` and call [the `clear()` method](https://github.com/laravel-zero/framework/blob/7e92a2d11a7d4963753d806b2cef217544198b93/src/Commands/BuildCommand.php#L178) which should restore the original Box configuration. 🤔

The `PCNTL` extension should be enabled on macOS (if installed through Brew) by default afaik. Unless macOS overwrites the `SIGINT` flow when using Ctrl+C.

**Comment by hylke94** [comment]
To confirm, this is still an issue. Just troubleshoot for two hours, to finally find this issue..

**Comment by owenvoke** [comment]
@hylke94, to confirm, what OS are you using?

**Comment by hylke94** [comment]
> @hylke94, to confirm, what OS are you using?

Latest Manjaro KDE
