### ISSUE TITLE
laravel-zero/installer fails to install

### ISSUE THREAD

**Issue by philip** [laravel-zero/laravel-zero#89]
The following command fails:
```
composer global require laravel-zero/installer
```

Output includes:
```
laravel-zero/framework v3.10.0 requires nunomaduro/laravel-desktop-notifier 1.3.* -> satisfiable by nunomaduro/laravel-desktop-notifier[v1.3.0].

...

Conclusion: don't install nunomaduro/laravel-desktop-notifier v1.3.0
```

However, installing a new project with composer works fine, such as:
```
composer create-project --prefer-dist laravel-zero/laravel-zero foo
```

**Comment by nunomaduro** [comment]
Hey @Philip, seems like you have an old version installed. 

Please perform:
`composer global laravel-zero/installer`
`composer global clear`
`composer global require laravel-zero/installer`

And tell me the results. 👍

**Comment by philip** [comment]
Hi @nunomaduro , attached is the output.

> ~/Sites
$ composer global remove laravel-zero/installer
Changed current directory to /Users/philip/.composer
laravel-zero/installer is not required in your composer.json and has not been removed
Package "laravel-zero/installer" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files

> ~/Sites 
$ composer global clear
Changed current directory to /Users/philip/.composer
Cache directory does not exist (cache-vcs-dir):
Clearing cache (cache-repo-dir): /Users/philip/.composer/cache/repo
Clearing cache (cache-files-dir): /Users/philip/.composer/cache/files
Clearing cache (cache-dir): /Users/philip/.composer/cache
All caches cleared.

> ~/Sites
$ composer global require laravel-zero/installer
Changed current directory to /Users/philip/.composer
Using version ^1.1 for laravel-zero/installer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

>  Problem 1
    - Conclusion: don't install laravel-zero/installer v1.1.1
    - Conclusion: don't install laravel-zero/installer v1.1.2
    - Conclusion: don't install laravel-zero/installer v1.1.3
    - Conclusion: don't install laravel-zero/installer v1.1.4
    - Conclusion: don't install laravel-zero/installer v1.1.5
    - Conclusion: don't install laravel-zero/installer v1.1.6
    - Conclusion: don't install laravel-zero/installer v1.1.7
    - Installation request for laravel-zero/installer ^1.1 -> satisfiable by laravel-zero/installer[v1.1.0, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v1.1.5, v1.1.6, v1.1.7].
    - laravel-zero/installer v1.1.0 requires laravel-zero/framework ~3.6 -> satisfiable by laravel-zero/framework[v3.10.0, v3.6.0, v3.6.1, v3.6.10, v3.6.11, v3.6.12, v3.6.2, v3.6.3, v3.6.4, v3.6.5, v3.7.0, v3.7.1, v3.7.2, v3.8.0, v3.8.1, v3.8.2, v3.9.0, v3.9.1, v3.9.2].
    - laravel-zero/framework v3.10.0 requires nunomaduro/laravel-desktop-notifier 1.3.* -> satisfiable by nunomaduro/laravel-desktop-notifier[v1.3.0].
    - laravel-zero/framework v3.6.0 requires nunomaduro/laravel-desktop-notifier 1.3.* -> satisfiable by nunomaduro/laravel-desktop-notifier[v1.3.0].
    - laravel-zero/framework v3.6.1 requires nunomaduro/laravel-desktop-notifier 1.3.* -> satisfiable by nunomaduro/laravel-desktop-notifier[v1.3.0].
    - laravel-zero/framework v3.6.10 requires nunomaduro/laravel-desktop-notifier 1.3.* -> satisfiable by nunomaduro/laravel-desktop-notifier[v1.3.0].
    - laravel-zero/framework v3.6.11 requires nunomaduro/laravel-desktop-notifier 1.3.* -> satisfiable by nunomaduro/laravel-desktop-notifier[v1.3.0].
    - laravel-zero/framework v3.6.12 requires nunomaduro/laravel-desktop-notifier 1.3.* -> satisfiable by nunomaduro/laravel-desktop-notifier[v1.3.0].
    - laravel-zero/framework v3.6.2 requires nunomaduro/laravel-desktop-notifier 1.3.* -> satisfiable by nunomaduro/laravel-desktop-notifier[v1.3.0].
    - laravel-zero/framework v3.6.3 requires nunomaduro/laravel-desktop-notifier 1.3.* -> satisfiable by nunomaduro/laravel-desktop-notifier[v1.3.0].
    - laravel-zero/framework v3.6.4 requires nunomaduro/laravel-desktop-notifier 1.3.* -> satisfiable by nunomaduro/laravel-desktop-notifier[v1.3.0].
    - laravel-zero/framework v3.6.5 requires nunomaduro/laravel-desktop-notifier 1.3.* -> satisfiable by nunomaduro/laravel-desktop-notifier[v1.3.0].
    - laravel-zero/framework v3.7.0 requires nunomaduro/laravel-desktop-notifier 1.3.* -> satisfiable by nunomaduro/laravel-desktop-notifier[v1.3.0].
    - laravel-zero/framework v3.7.1 requires nunomaduro/laravel-desktop-notifier 1.3.* -> satisfiable by nunomaduro/laravel-desktop-notifier[v1.3.0].
    - laravel-zero/framework v3.7.2 requires nunomaduro/laravel-desktop-notifier 1.3.* -> satisfiable by nunomaduro/laravel-desktop-notifier[v1.3.0].
    - laravel-zero/framework v3.8.0 requires nunomaduro/laravel-desktop-notifier 1.3.* -> satisfiable by nunomaduro/laravel-desktop-notifier[v1.3.0].
    - laravel-zero/framework v3.8.1 requires nunomaduro/laravel-desktop-notifier 1.3.* -> satisfiable by nunomaduro/laravel-desktop-notifier[v1.3.0].
    - laravel-zero/framework v3.8.2 requires nunomaduro/laravel-desktop-notifier 1.3.* -> satisfiable by nunomaduro/laravel-desktop-notifier[v1.3.0].
    - laravel-zero/framework v3.9.0 requires nunomaduro/laravel-desktop-notifier 1.3.* -> satisfiable by nunomaduro/laravel-desktop-notifier[v1.3.0].
    - laravel-zero/framework v3.9.1 requires nunomaduro/laravel-desktop-notifier 1.3.* -> satisfiable by nunomaduro/laravel-desktop-notifier[v1.3.0].
    - laravel-zero/framework v3.9.2 requires nunomaduro/laravel-desktop-notifier 1.3.* -> satisfiable by nunomaduro/laravel-desktop-notifier[v1.3.0].
    - Conclusion: don't install nunomaduro/laravel-desktop-notifier v1.3.0

> Installation failed, reverting ./composer.json to its original content.

**Comment by nunomaduro** [comment]
There is clearly something weird on this. Please perform:

`composer global remove "laravel-zero/framework"`

`composer global remove "nunomaduro/laravel-desktop-notifier"`

Then try again.

**Comment by philip** [comment]
I barely understand/speak composer but I get the same result as those aren't installed. Here's my ~/.composer file:
```
{
    "require": {
        "tightenco/lambo": "^0.4.1",
        "laravel/installer": "^1.4",
        "laravel/valet": "^2.0",
        "psy/psysh": "@stable"
    }
}
```

**Comment by nunomaduro** [comment]
Sorry @philip. I have no ideia. Let's leave this issue open to understand if someone is having the same problem as you.

**Comment by TNovalis** [comment]
@nunomaduro Do you happen to **not** have valet?

**Comment by nunomaduro** [comment]
@TNovalis I have Valet. Do you have this issue?

**Comment by TNovalis** [comment]
@nunomaduro Did you install valet before or after *laravel-zero/installer*

**Comment by nunomaduro** [comment]
@TNovalis Valet before. Why?

**Comment by TNovalis** [comment]
Hmm... since here's how I fixed it.
`composer global remove laravel/valet`
`composer global update`
`composer global require laravel-zero/installer`
`composer global require laravel/valet`
(Technically since it was *cpriego/linux-valet* but they have nearly the same dependencies)

**Comment by nunomaduro** [comment]
@Philip Try this:

`composer global update`
`composer global remove laravel-zero/installer`
`composer global clear`
`composer global require laravel-zero/installer`

**Comment by philip** [comment]
@nunomaduro That alone did not fix it but following @TNovalis's steps did. In other words, uninstalling `laravel/valet` first allowed `laravel-zero/installer` to install.

Unrelated, sorry for filing this issue against `laravel-zero/laravel-zero` instead of `laravel-zero/installer` :flushed:

**Comment by TNovalis** [comment]
It was a dependency issue since `laravel/valet` depends on `illuminate/container` which depends on `illuminate/contracts` which `laravel-zero/installer` depends on.

Running `composer global require laravel-zero/installer --update-with-dependencies` *should* fix the issue without all the steps, I *think*.

**Comment by nunomaduro** [comment]
@TNovalis @philip Thanks a lot for this info. I will update the docs tonight with some kind of `troubleshooting` section.
